### ISSUE TITLE
Error - Invalid GUIClip Stack Popping

### ISSUE THREAD

**Issue by DingoDjango** [KiameV/rimworld-modsync-rw#1]
Installed ModSync 1.0 release from the .zip file in Releases on a naked RimWorld 1.0

It spams "Invalid GUIClip Stack Popping" in the Unity console (not even RW console...)

[Here's an image showcasing the error](https://i.imgur.com/I1CG01a.png)

**Comment by KiameV** [comment]
I have seen this as well. I've commented out all the rendering code and it still showed up. I believe this is an error in RimWorld not this mod.

I will keep this open as I do plan to post a bug report in the RW forums.

**Comment by DingoDjango** [comment]
Yeah I believe RW is currently showing internal Unity dev stuff. They might've published a Debug version as the unstable build.

**Comment by KiameV** [comment]
Heh i feel dumb. Nope it's my side. I took another look and it was a glaring omission on my part. I did comment out everything EXCEPT for an GUI.EndGroup which has no StartGroup. Fix incommng.

**Comment by KiameV** [comment]
Fixed. New version is now available in the Release section. Thanks Dingo
