### ISSUE TITLE
"Update required" if local mod version is newer than available version

### ISSUE THREAD

**Issue by DingoDjango** [KiameV/rimworld-modsync-rw#3]
Let's say a mod author releases a beta or something that does not update the available version. Their mod is v1.1 and the available version is still v1.0

ModSyncRW will highlight that mod and recommend updating. I don't think that is intended.

Also, while testing this I saw that after entering and exiting the ModSync window a few times it stopped successfully fetching available versions altogether.

**Comment by KiameV** [comment]
Someone finally noticed!

I've been debating how I want to handle this case. Should I color it something different than red, like orange? For example, the mod maker roles back a release; but the better course is just increment the version and re-release the previous version as the new one.

I have the logic in there already to detect this case, just wasn't using it. I'll consider having this in the next release. (where it'll only be red if the local version is less than the remote)

**Comment by DingoDjango** [comment]
It should definitely not be the same colour as "old version" in my opinion.

**Comment by KiameV** [comment]
Resolved
