### ISSUE TITLE
Mod Catalog

### ISSUE THREAD

**Issue by AaronCRobinson** [KiameV/rimworld-modsync-rw#4]
Can we support having a Mod Catalog where people can easily add mods to be downloaded initially without the need to search or use an external service. This of course would only include mods that have included the ModSync.xml but could either be a small file (or sqlite) storing very basic info on mods (e.g. category, name, dl link).

**Comment by KiameV** [comment]
This was what the original ModSync did. There was little support and there were costs involved for hosting. The approach ModSync RW is taking is to have no single source of hosting. In the end there is no possibility for a centralized database/catalog with this model.
